JC = javac
JFLAGS = -g
CLASSES = \
        DisplayCharacters.java \
        Scheduler.java\
	Parser.java\
	Lesson.java\
	UserInput.java

all: classes

classes:
	$(JC) $(JFLAGS) $(CLASSES)

clean:
	rm *.class

